#! /usr/bin/env bash
#
# Entrypoint for urdu building toolchain which correctly invokes the underlying tools

if [[ "$1" = "bash" ]];
then
    docker run --rm -it -v "$(pwd -P)":/src -p 8000:8000 --entrypoint=bash xelatex-urdu
else
    docker run --rm -v "$(pwd -P)":/src -p 8000:8000 xelatex-urdu "$@"
fi
